WebAppBankDocker/Models/ErrorViewModel.cs
namespace WebAppBankDocker.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAppBankDocker/Models/UserLogin.cs
namespace WebAppBankDocker.Models
{
    public class UserLogin
    {
        public string? UserName { get; set; }
        public string? Password { get; set; }
    }
}

WebAppBankDocker/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebAppBankDocker.Models;

namespace WebAppBankDocker.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAppBankDocker/Controllers/UserLoginController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppBankDocker.Models;

namespace WebAppBankDocker.Controllers
{
    public class UserLoginController : Controller
    {
        readonly List<UserLogin> users = new List<UserLogin>()
        {
            new UserLogin() {UserName="Sam" ,Password="Sam@123"},
            new UserLogin() {UserName="Ram" ,Password="Ram@123"},
            new UserLogin() {UserName="Sameer" ,Password="Sameer@123"},
            new UserLogin() {UserName="Amir" ,Password="Amir@123"},
        };
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(string username, string password)
        {
            foreach (var user in users)
            {
                if (user.UserName == username && user.Password == password)
                {
                    return RedirectToAction("Dashboard");
                }
                ViewBag.ErrorMessage = "Invalid username or password";
            }
            return View();
        }
        public IActionResult Dashboard()
        {
            return View();
        }
        public IActionResult Logout()
        {
            return RedirectToAction("Login");
        }
    }
}

WebAppBankDocker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bank Application</h1>
    <p>welcome to our bank application</p>
    <p><a href="http://localhost:5186/UserLogin/Login" class="btn btn-primary btn-md">Go to Login Page &raquo;</a></p>
</div>

WebAppBankDocker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppBankDocker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppBankDocker.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppBankDocker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserLogin" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebAppBankDocker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebAppBankDocker/Views/UserLogin/Dashboard.cshtml
@page
@model Views_UserLogin_Dashboard
<h1>Welcome to the Dashboard!</h1>
<p>Account </p>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<p>
    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapseExample">
        Account Number
    </button>
</p>

<div class="collapse" id="collapse1">
    98761234502
</div>
<br />
<br />
<p>
    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapseExample">
        Account Balence
    </button>
</p>
<div class="collapse" id="collapse2">
    9876543210
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<br />
<br />
<form method="post" asp-action="Login">
    <button type="submit">Logout</button>
</form>

WebAppBankDocker/Views/UserLogin/Login.cshtml
model UserLogin

<h1>Login</h1>
@if (!string.IsNullOrEmpty(ViewBag.ErrororMessage))
{
    <p>ViewBag.ErrorMessage</p>
}
<form method="post" asp-action="Login">
    <input type="text" name="Username"><br /><br />
    <input type="password" name="password"><br /><br />
    <button type="submit">Login</button>
</form>